"""Remove show_all

Revision ID: 0a2073ee6172
Revises: 84669d3bd9a0
Create Date: 2026-01-23 12:53:16.769324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a2073ee6172'
down_revision = '84669d3bd9a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag_group', schema=None) as batch_op:
        batch_op.alter_column('show_size',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('show_all')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_all', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.alter_column('show_size',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
