"""rename bookmark and add indices

Revision ID: 14161e50054c
Revises: 2b849af2d1ef
Create Date: 2026-01-21 11:53:16.805838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14161e50054c'
down_revision = '2b849af2d1ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bookmark', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_asset_bookmark'), ['bookmark'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_favorite'), ['favorite'], unique=False)
        batch_op.drop_column('bookmarked')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bookmarked', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_asset_favorite'))
        batch_op.drop_index(batch_op.f('ix_asset_bookmark'))
        batch_op.drop_column('bookmark')

    # ### end Alembic commands ###
