"""add bookmarked and should delete to asset

Revision ID: 2b849af2d1ef
Revises: e38816a2f6e9
Create Date: 2026-01-21 11:12:46.052391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b849af2d1ef'
down_revision = 'e38816a2f6e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('should_delete', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('bookmarked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_column('bookmarked')
        batch_op.drop_column('should_delete')

    # ### end Alembic commands ###
