"""Allow tag per line

Revision ID: 397e6d3521fa
Revises: e4b6c41c2caf
Create Date: 2026-01-26 13:18:06.217203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '397e6d3521fa'
down_revision = 'e4b6c41c2caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_per_line', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag_group', schema=None) as batch_op:
        batch_op.drop_column('tag_per_line')

    # ### end Alembic commands ###
