"""Initial migration.

Revision ID: 47851d95600e
Revises: 
Create Date: 2025-03-15 15:42:21.754679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47851d95600e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset')
    # ### end Alembic commands ###
