"""Asset cascade delete tag associations

Revision ID: 77beba829296
Revises: 397e6d3521fa
Create Date: 2026-02-02 10:36:23.752471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77beba829296'
down_revision = '397e6d3521fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_tag', schema=None) as batch_op:
        batch_op.drop_constraint('asset_tag_asset_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'asset', ['asset_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_tag', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('asset_tag_asset_id_fkey', 'asset', ['asset_id'], ['id'])

    # ### end Alembic commands ###
