"""Category tag group table

Revision ID: 812f96e54e2f
Revises: f9589e2f94f9
Create Date: 2025-07-16 17:51:31.831232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812f96e54e2f'
down_revision = 'f9589e2f94f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_tag_group',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tag_group_id', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_group_id'], ['tag_group.id'], ),
    sa.PrimaryKeyConstraint('name', 'tag_group_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_tag_group')
    # ### end Alembic commands ###
