"""Add size column

Revision ID: 84669d3bd9a0
Revises: 14161e50054c
Create Date: 2026-01-23 12:46:49.226343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84669d3bd9a0'
down_revision = '14161e50054c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_size', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag_group', schema=None) as batch_op:
        batch_op.drop_column('show_size')

    # ### end Alembic commands ###
