"""Tags can have same name if diff tag groups

Revision ID: b4178d370eda
Revises: 77beba829296
Create Date: 2026-02-04 11:30:58.268818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4178d370eda'
down_revision = '77beba829296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_constraint('tag_name_key', type_='unique')
        batch_op.create_unique_constraint('uix_tag_group_name', ['tag_group_id', 'name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_constraint('uix_tag_group_name', type_='unique')
        batch_op.create_unique_constraint('tag_name_key', ['name'])

    # ### end Alembic commands ###
