"""Add index to Asset.path

Revision ID: bb84f8b0ef10
Revises: b4178d370eda
Create Date: 2026-02-06 09:46:56.788211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb84f8b0ef10'
down_revision = 'b4178d370eda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_path'), ['path'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_path'))

    # ### end Alembic commands ###
