"""Adding attributes to tag group

Revision ID: f9589e2f94f9
Revises: 2e5ce734e9cf
Create Date: 2025-07-10 15:13:57.245423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9589e2f94f9'
down_revision = '2e5ce734e9cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ui_addable', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('multiselect', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('show_all', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag_group', schema=None) as batch_op:
        batch_op.drop_column('show_all')
        batch_op.drop_column('multiselect')
        batch_op.drop_column('ui_addable')

    # ### end Alembic commands ###
